emails = [
    {"id": 1, "subject": "Meeting tomorrow", "body": "We have a meeting at 10 AM", "type": "work"},
    {"id": 2, "subject": "50% OFF SALE!!!", "body": "Huge discounts available", "type": "spam"},
    {"id": 3, "subject": "Dinner tonight?", "body": "Want to grab dinner?", "type": "personal"},
    {"id": 4, "subject": "Project deadline", "body": "Submit by EOD", "type": "work"},
    {"id": 5, "subject": "You've won a prize!", "body": "Click here to claim", "type": "spam"},
    {"id": 6, "subject": "Weekend trip", "body": "Let's plan a trip", "type": "personal"},
    {"id": 7, "subject": "Client feedback", "body": "Please review changes", "type": "work"},
    {"id": 8, "subject": "Crypto investment", "body": "Earn fast money", "type": "spam"},
    {"id": 9, "subject": "Birthday party", "body": "You're invited!", "type": "personal"},
    {"id": 10, "subject": "Team sync", "body": "Weekly sync-up meeting", "type": "work"},

    {"id": 11, "subject": "Urgent: Server Down", "body": "Fix immediately", "type": "work"},
    {"id": 12, "subject": "FREE iPhone Giveaway", "body": "Click to win", "type": "spam"},
    {"id": 13, "subject": "Movie night?", "body": "Let's watch something", "type": "personal"},
    {"id": 14, "subject": "Invoice attached", "body": "Please review invoice", "type": "work"},
    {"id": 15, "subject": "Work from home opportunity", "body": "Earn $500/day", "type": "spam"},
    {"id": 16, "subject": "Family dinner", "body": "Sunday night dinner", "type": "personal"},
    {"id": 17, "subject": "Quarterly report", "body": "Prepare slides", "type": "work"},
    {"id": 18, "subject": "Bitcoin doubling scheme", "body": "Send 1 BTC get 2", "type": "spam"},
    {"id": 19, "subject": "Catch up soon", "body": "Long time no see!", "type": "personal"},
    {"id": 20, "subject": "Code review needed", "body": "Review PR #42", "type": "work"},

    {"id": 21, "subject": "Important: Update your account", "body": "Please verify your bank details urgently", "type": "spam"},
    {"id": 22, "subject": "Re: Meeting notes", "body": "Here are the notes from today's meeting", "type": "work"},
    {"id": 23, "subject": "Hey, check this out", "body": "This looks like a great opportunity!", "type": "spam"},
    {"id": 24, "subject": "Lunch?", "body": "Are you free for lunch today?", "type": "personal"},
    {"id": 25, "subject": "Security Alert", "body": "Suspicious login detected", "type": "work"},
    {"id": 26, "subject": "Congratulations! You're selected", "body": "Claim your reward now", "type": "spam"},
    {"id": 27, "subject": "Follow up", "body": "Just checking in on our last conversation", "type": "work"},
    {"id": 28, "subject": "Party this weekend", "body": "Don't miss it!", "type": "personal"},
    {"id": 29, "subject": "Invoice overdue", "body": "Payment pending", "type": "work"},
    {"id": 30, "subject": "Limited time offer", "body": "Act now!", "type": "spam"}
]