[project]
name = "email-inbox-env"
version = "0.1.0"
description = "Email Inbox Manager OpenEnv environment"
authors = [
    { name = "Your Name" }
]

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "openenv>=0.2.0"
]

[project.scripts]
server = "app:app"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
